### ISSUE TITLE
Narrator/NVDA not annoucing the page name when clicking on the "Previous" and "Next" page button: A11y_Maow_Follow a workshop_Previous_ScreenReader.

### ISSUE THREAD

**Issue by AnKushSingh05** [microsoft/moaw#120]
### GitHub Tags
#A11yTCS; #A11ySev2; #ChromiumEdge; #WCAG1.3.1; #Win11; #GH_Maow_Web_Mar24; #DesktopWeb; #Maow; #Info and Relationships; #AILimited; #A11yMAS;

### Actual Result:
Narrator/NVDA not announcing the page name when clicking on the "Previous" and "Next" page button.

### Expected Result:
Narrator/NVDA not announcing the page name when clicking on the "Previous" and "Next" page button.

### Environment Details:
Application Name: Maow
#URL: https://moaw.dev/catalog/
OS: Windows 11 Enterprise 23H2 (OS build 22631.3296)
Microsoft Edge: Version 122.0.2365.92 (Official build) (64-bit)
Narrator
NVDA Version: 2023.3.4

### Repro Steps:

1. Hit the URL https://moaw.dev/workshop/create-workshop/
2. Create A Workshop screen will get open.
3. TAB till "Initial setup" control present in left navigation and press ENTER.
4. TAB till "previous" control.
5. Verify whether the Narrator/NVDA is announcing the page name when clicking on the "Previous" and "Next" page button

### User Impact:
Screen reader will not know about the next or previous page name if screen reader is not announcing it.
### 
### Attachment:
**NVDA:**
![Bug_120](https://github.com/microsoft/moaw/assets/124244478/5926921e-611c-4973-9021-33923a38c6ce)
**Narrator**
![Bug_120_Narrator](https://github.com/microsoft/moaw/assets/124244478/3d7c337c-e863-4674-b155-9a6986ead70a)

**Comment by sinedied** [comment]
@AnKushSingh05 this one has been fixed, could you validate it?

**Comment by AnKushSingh05** [comment]
Verified the issue in below environment
https://moaw.dev/workshop/create-workshop/?step=2#conditional-content
Issue is fixed. Hence closing the bug
![Screenshot (1960)](https://github.com/microsoft/moaw/assets/124244478/fe80aa7a-d67c-44fe-9b5c-67c46a6e251e)
