### ISSUE TITLE
Keyboard focus is not going to the top of the page when we are pressing the "Next" page button: A11y_Maow_Follow a workshop_Previous_FocusOrder.

### ISSUE THREAD

**Issue by AnKushSingh05** [microsoft/moaw#123]
### GitHub Tags
#A11yTCS; #A11ySev2; #ChromiumEdge; #WCAG2.4.3; #Win11; #GH_Maow_Web_Mar24; #DesktopWeb; #Maow; #FocusOrder; #AILimited; #A11yMAS;

### Environment Details:
Application Name: Maow
#URL: https://moaw.dev/catalog/
OS: Windows 11 Enterprise 23H2 (OS build 22631.3296)
Microsoft Edge: Version 122.0.2365.92 (Official build) (64-bit)

### Repro Steps:

1. Hit the URL https://moaw.dev/workshop/create-workshop/
2. Create A Workshop screen will get open.
3. TAB till "Initial setup" control present in left navigation and press ENTER.
4. TAB till "previous" control.
5. Verify whether the Keyboard focus is going to the top of the page when we are pressing the "Next" page button or not.

### Actual Result:
Keyboard focus is not going to the top of the page when we are pressing the "Next" page button.

### Expected Result:
Keyboard focus should go to the top of the page when we are pressing the "Next" page button.
### User Impact:
Keyboard user will face difficulty in navigating through the page.
### Attachment:
![Bug_123](https://github.com/microsoft/moaw/assets/124244478/f7cabaa4-e0bc-4f9a-9e97-46262f11f187)

**Comment by sinedied** [comment]
@AnKushSingh05 this one has been fixed, could you validate it?

**Comment by AnKushSingh05** [comment]
Verified the issue in below environment
https://moaw.dev/
Issue is fixed. Hence closing the bug


https://github.com/microsoft/moaw/assets/124244478/ce86c2d0-3a50-444e-ba21-a4bd96a7fc4b
