### ISSUE TITLE
Ensures all ARIA attributes have valid values:A11y_Maow_AI4W.

### ISSUE THREAD

**Issue by AnKushSingh05** [microsoft/moaw#135]
### GitHub Tags
#A11yTCS; #A11ySev2; #WCAG4.1.2; #Win11; #GH_Maow_Web_Mar24; #DesktopWeb; #Maow;#A11yMAS;#aria-valid-attr-value;#Accessibility;#AI4W;#WCP;#P3_WCP;

### Environment Details:
Application Name: Maow
#URL: https://moaw.dev/workshop/swa-gatsby-portfolio/?step=2
Operating system: Windows 11
Enterprise Insider Preview 22H2 (OS build 22631.3672)
Microsoft Edge: Version 125.0.2535.92 (Official build) (64-bit)

### Repro Steps:

1. Hit the URL: https://moaw.dev/workshop/swa-gatsby-portfolio/?step=2
2. Run AI4W
3. Verify wether the Ensures all ARIA attributes have valid values.

 
### Issue: 
Ensures all ARIA attributes have valid values (aria-valid-attr-value - https://accessibilityinsights.io/info-examples/web/aria-valid-attr-value)
### Similar issue is also observed in below links
- https://moaw.dev/workshop/swa-gatsby-portfolio/?step=1
- https://moaw.dev/workshop/swa-gatsby-portfolio/?step=3#the-configindexjs-file
 
### Target application:
 Portfolio Workshop - Deploy your app - https://moaw.dev/workshop/swa-gatsby-portfolio/?step=2
 
### Element path:
 .\"octicon
 
### Snippet: 
<svg version="&quot;1.1&quot;" width="&quot;14&quot;" height="&quot;14&quot;" viewBox="&quot;0" 0="" 16="" 16&quot;="" class="&quot;octicon" octicon-link-external="" external-link&quot;="" aria-hidden="&quot;true&quot;">
 
### How to fix: 
Fix all of the following:

-   Invalid ARIA attribute value: aria-hidden=""true""

 
### Environment: 
Microsoft Edge version 125.0.0.0
==== 
This accessibility issue was found using Accessibility Insights for Web 2.42.0 (axe-core 4.8.4), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

### Attachment:
![image (3)](https://github.com/microsoft/moaw/assets/124244478/91cb3962-5185-4d99-b0cb-63b51f41218d)
![image (2)](https://github.com/microsoft/moaw/assets/124244478/bb89490e-73a0-4e69-bf7c-573c067ba2e3)
![image (1)](https://github.com/microsoft/moaw/assets/124244478/eaf9f182-1e97-40b0-ab68-2106ff12b172)

**Comment by kupatkar99** [comment]
Github Tags:#Rev:yaja;

**Comment by Yash14j** [comment]
GithubTags:#Rev:yaja;
