### ISSUE TITLE
Confusing link on "Platform" section of website

### ISSUE THREAD

**Issue by tessawiedmann** [microsoft/moaw#19]
https://github.com/microsoft/moaw/blob/ea4c304aa57e84ad083b3f85ef4bbfad47b06dc0/website/src/app/home/home.component.ts#L57

The "How to create and host your workshop" sentence under "Platform"  here
![image](https://user-images.githubusercontent.com/21200448/204329735-463b38ec-66fe-4951-9c0e-b42333c657bc.png)

links to the workshop Catalog- is this intended?

**Comment by sinedied** [comment]
Good catch!

It was intended to link to the tutorial, I'll fix that thanks!
