### ISSUE TITLE
[Feature] Preview private workshops

### ISSUE THREAD

**Issue by cmaneu** [microsoft/moaw#22]
I'm creating a new workshop. For now, it is hosted in a private repository. I would like to be able to preview it.
Some ideas: 
- Being able to pass to MOAW the full URL of the markdown to render
- while locally execute MOAW, being able to pass local path (don't like it for security reasons)

Some ideas I don't want to use: 
- Symbolic links
- git submodules

**Comment by cmaneu** [comment]
## Workaround #1 - symlinks
- Fork/Clone this repo
- Create a symlink from your workshop repo code into ./workshops

## Workaround #2 - submodule and codespaces
_It should work but it doesn't_
- Fork/Clone this repo
- If the private repo for the workshop is not under your account, fork it as well
- Update `devcontainer.json` to add permissions to your workshop repo
```json
	"customizations": {
		"codespaces": {
		      "repositories": {
			"cmaneu/my-workshop": {
			  "permissions": {
			    "permissions": "read-all"
			  }
			}
		      }
		    },
		// Configure properties specific to VS Code.
		"vscode": ...
	},
```
- Add the submodule `git submodule add -b main https://github.com/cmaneu/my-workshop.git workshops/my-workshop`
- 

Reference https://docs.github.com/en/codespaces/managing-your-codespaces/managing-repository-access-for-your-codespaces

**Comment by sinedied** [comment]
Done https://github.com/microsoft/moaw/tree/main/packages/cli 🙂
