### ISSUE TITLE
[Issue] Workshop in error 404

### ISSUE THREAD

**Issue by olivMertens** [microsoft/moaw#28]
Workshop error 404:

- Build your resum website with .net
- Predict future water consumption withg ML .NET
- Javascript portfolio Site with github codespaces
- Build a mobile App to track water consumtion
- Python http api for use with github codespaces

**Comment by olivMertens** [comment]
it seems it's about all external workshop from here
https://microsoft.github.io/workshop-library/

**Comment by sinedied** [comment]
Some of them are working, some not. Seems they're missing a part of the URL, maybe something changed on their repo.
