### ISSUE TITLE
How to test it locally ?

### ISSUE THREAD

**Issue by lgmorand** [microsoft/moaw#33]
The contribute page seems deprecated and I'm stupid enought not to be able to test my new workshop locally :'(

@sinedied need ya because I need to play it with customer next Thursday :D

1- What is "website" ? seems that a website is built AFTER npm install but not before

```
cd website
npm install
npm start
```

2- 
`This will start a local development server at http://localhost:4200.

You can open your local workshop by navigating to http://localhost:4200/workshops/?src=<workshop_folder_name>.`

http://localhost:4200 => Cannot GET /
It seems that it is configured to run on http://localhost:4200/**moaw** instead

But from that point where I get the home page perfectly functionning, impossible to test my workshop (named github-copilot)
I tried
http://localhost:4200/workshops/github-copilot  => Cannot GET /workshops/github-copilot
http://localhost:4200/workshops/?src=github-copilot => Cannot GET /workshops/
http://localhost:4200/moaw/workshops/github-copilot => get redirected to /
http://localhost:4200/moaw/workshops/?src=github-copilot => get redirected  to /

What am I missing ? I also tried with an existing workshop, same behavior

**Comment by lgmorand** [comment]
Bon j'avance un peu. je suis parti du côté de la génération du fichier workshop.json et ca m'a permis de comprendre que contrairement à ce qu'indiqué, c'est pas workshop**s** mais workshop

et maintenant j'ai un beau "Could not load workshop :("

mais je vais continuer :)

**Comment by lgmorand** [comment]
![image](https://user-images.githubusercontent.com/6757079/235309569-d123b23c-9f1f-4010-813b-2a4420b7e412.png)
 yeahhhhhh.

Bon alors, finalement je sais pas si c'est le parsing en live qui deconnait mais quand j'ai regardé les logs de la construction de la DB, il me trouvait des erreurs dans mon fichier et en les corrigeant, l'atelier etait ajouté au catalogue et l'affichage marchait.


conclusion: faut qu'on mette à jour la page contributing :D

**Comment by lgmorand** [comment]
je ferme pas le temps qu'on corrige. j'aimerais ton avis Yohan. c'était juste un soucis de parsing de fichier ET un problème de path ?
ou faut absolument contruire la DB pour que ca fonctionne ?

**Comment by sinedied** [comment]
Pas besoin de la construction de la DB, ca sert uniquement a lister le workshop pas a l'afficher. Par contre il faut que le yaml du frontmatter soit valide, sinon ca pose souci pour l'affichage.

Effectivement la doc de contribution avait besoin d'une mise a jour, merci pour le fix 🙂
Il faut aussi que je rajoute des infos car maintenant il y a la CLI qui simplifie le process.

Si jamais ca peut service à d'autre, la doc qui est toujours à jour normalement est celle-ci: https://microsoft.github.io/moaw/workshop/create-workshop/

**Comment by lgmorand** [comment]
ah je suis couillon parce qu'en plus, j'ai suivi ce tuto sur les premieres etapes et après j'ai switché sur contributing :D
