### ISSUE TITLE
Container wrap

### ISSUE THREAD

**Issue by jmppyo** [microsoft/moaw#38]
I would like to wrap moaw into a container to run for private internal usage for my workplace. Is the a way to go about this?

**Comment by sinedied** [comment]
You can definitely do it, though we currently don't provide support for such a use case.
It should not be too difficult, as the website is a static build, any HTTP server host could work.

You can look at the GitHub deployment workflow to get an idea of what's needed to build the app: https://github.com/microsoft/moaw/blob/main/.github/workflows/deploy.yml

The 2 most important steps are:
- set the GITHUB_REPO_URL (it's used as the base URL to load workshops) and build the DB with `npm run create:db` 
- build the website with `npm run build:website` (you may need to customize the ng build command with the `--base-href` flag to change it if needed)
- package everything into a container, and use a web server with a config supporting SPA to host the website

I you get a working container configuration, we would welcome a PR 😉
