### ISSUE TITLE
[Proposal] Workshop Ms learn OpenAI

### ISSUE THREAD

**Issue by olivMertens** [microsoft/moaw#47]
In your opinion do we have to register this workshop learn in Moaw ?

https://microsoftlearning.github.io/mslearn-openai/Instructions/Labs/01-get-started-azure-openai.html
And subsequently
https://microsoftlearning.github.io/mslearn-openai/

**Comment by sinedied** [comment]
I would say yes, but this one is strange: is name implies that it should (might?) be published on MS Learn, and in that case it would not make sens to add it on Moaw. But currently it's not, so...

**Comment by olivMertens** [comment]
It seems the exercice was simplier to implement in gh pages outside a repository like moaw :)

**Comment by mayanashit** [comment]
Yes!, but beginner has some challenges, I suppose.
