### ISSUE TITLE
[Issue] workshop: Analyzing Wildlife Data with Microsoft Fabric (2)

### ISSUE THREAD

**Issue by trantrongw** [microsoft/moaw#81]
In https://moaw.dev/workshop/fabric-e2e-serengeti/?step=7#transforming-our-dataset
I got this error:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[46], line 28
     25             labels = self.data.iloc[idx, 1]
     26             return image, labels
---> 28 transform = transforms.Compose([
     29     transforms.Resize((224, 224)),
     30     transforms.ToTensor()
     31 ])
     33 train_set = CustomDataset("/lakehouse/default/Files/images/train/", transform=transform)
     34 test_set = CustomDataset("/lakehouse/default/Files/images/test/", transform=transform)

NameError: name 'transforms' is not defined

**Comment by BethanyJep** [comment]
Hello, I've updated the code to import transforms, you can use: 
`from torchvision import transforms`
