### ISSUE TITLE
Workshop not found is "/" is missing

### ISSUE THREAD

**Issue by lgmorand** [microsoft/moaw#97]
https://moaw.dev/workshop/github-copilot/ => OK
https://moaw.dev/workshop/github-copilot => KO

tu vas me dire que c'est normal mais en meme temps je sais plus où ni comment j'ai eu à un moment une URL sans "/".

**Comment by sinedied** [comment]
Oui les 2 sont interprétés différemment:
- https://moaw.dev/workshop/github-copilot/ => va chercher https://moaw.dev/workshop/github-copilot/workshop.md
- https://moaw.dev/workshop/github-copilot => va chercher https://moaw.dev/workshop/github-copilot.md

Après j'ai corrigé un bug avec la CLI avant les vacances, en test local dans certains cas l'URL affichée dans la console n'était pas la bonne, donc possible que ca soit lié. Par contre la release n'est pas encore passée j'ai un bug sur l'outil, ca va arriver rapidement
